### bbs

GET http://localhost:63002/bbs/read/30

### PAGE

GET http://dev-b.zcvfcat.ga/bbs/1

### INSERT
POST http://dev-b.zcvfcat.ga/bbs/ HTTP/1.1
content-type: application/json
User-Agent: rest-client

{
    "name" : "1",
    "pw" : "1",
    "title" : "1",
    "content" : "1"
}

### UPDATE
PUT  http://dev-b.zcvfcat.ga/bbs/ HTTP/1.1
content-type: application/json
User-Agent: rest-client

{
    "idx" : "20",
    "name" : "test",
    "pw" : "1",
    "title" : "60",
    "content" : "60"
}

### DELETE
DELETE  http://localhost:63002/bbs/76 HTTP/1.1
content-type: application/json
User-Agent: rest-client

{
    "idx" : "76",
    "name" : "13",
    "pw" : "13"
}
// "proxy": "http://dev-b.zcvfcat.ga",
// "proxy": "http://localhost:63002",

###

GET http://dev-b.zcvfcat.ga/comment/1