// export {default} from 'store/module/bbs/defaultbbs.js'
export {default as list} from 'store/module/bbs/list'
export {default as read} from 'store/module/bbs/read'
export {default as create} from 'store/module/bbs/create'
export {default as update} from 'store/module/bbs/update'
export {default as delete} from 'store/module/bbs/delete'